# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
