# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a60128d115af0c555fe5a39cd12f8cb0140e874bdd63131902a63d1feec447de44cb5ab3920d850606d99411f2d987d74642877e80fc1c3b0732e9f3bb04e1f9

test:
  secret_key_base: ccbea23629ee0877d60a5f2a3430e48e396bae64b5626aa9594f142d33cd250e4b3245731a4db36f9466282ccc0a3c4e1af82276f872ecafe4fa6229e3746788

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
