# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 213ff0c561d798311f93efe2ce5db93195f6707187a06f7050881a18e920c2dc16a5b459efc84afdaa16616b33a194426bf68c823671b11aab22ef0099b6d965

test:
  secret_key_base: 6f1a21373e48e49637fea44661894415ea4e343e786497bdca3f73e16e88eb3cf3654532d940987d920748716d390e7eb15ae87c6a3d46afcd7e31f5cdd672f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
